# Generated by Django 4.2.1 on 2023-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(max_length=65, null=True),
        ),
    ]
