# Generated by Django 4.2.1 on 2023-06-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_preparation_time_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='authot',
            new_name='author',
        ),
    ]
