# Generated by Django 4.2.1 on 2023-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_authot_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipe/covers/%Y/%m/%d'),
        ),
    ]
